#!/usr/bin/env bash
#0. World wide web

function get_subdomain_info {
    local domain=$1
    local subdomain=$2

    dig_output=$(dig +short "$subdomain.$domain" | awk 'NR==1')
    if [[ -n $dig_output ]]; then
        echo "The subdomain $subdomain is a A record and points to $dig_output"
    fi
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"; do
        get_subdomain_info "$domain" "$sub"
    done
else
    get_subdomain_info "$domain" "$subdomain"
fi

