#!/usr/bin/env bash
#Install nginx on your web-01

apt-get -y update
apt-get -y install nginx

#Nginx should be listening on port 80
sudo ufw allow 'HTTP' 

#HTML page
echo "Hello World!" > /var/www/html/index.html

#restart nginx
service nginx restart
