#!/usr/bin/env bash
#configure your Nginx server so that
#/redirect_me is redirecting to another page.

apt-get -y update
apt-get -y install nginx

#Nginx should be listening on port 80
sudo ufw allow 'HTTP' 

#HTML page
echo "Hello World!" > /var/www/html/index.html

#redirection confg
confg_path=/etc/nginx/sites-available/default
sed -i "/server_name _;/a \\\trewrite ^\\/redirect_me https:\\/\\/www.alxafrica.com permanent;" $confg_path

#restart nginx
service nginx restart
