#!/usr/bin/env bash
#Configure your Nginx server so that
#/redirect_me is redirecting to another page.

apt-get -y update
apt-get -y install nginx

#Nginx should be listening on port 80
ufw allow 'HTTP' 

#HTML page
echo "Hello World!" > /var/www/html/index.html

#redirection confg
sed -i '/server_name _;/a location \/redirect_me {\\treturn 301 https:\/\/alxafrica.com\/};' /etc/nginx/sites-available/default
#restart nginx
service nginx restart
