#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page
# and set a custom 404 page.

# Update package lists and install Nginx
apt-get -y update
apt-get -y install nginx

# Allow HTTP traffic
sudo ufw allow 'HTTP'

# Create the default HTML page
echo "Hello World!" > /var/www/html/index.html

# Create the custom 404 error page
echo "<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>Ceci n'est pas une page</h1>
</body>
</html>" > /var/www/html/404.html

# Configure redirection and custom 404 page
config_path=/etc/nginx/sites-available/default
sed -i "/server_name _;/a \\\trewrite ^\\/redirect_me https:\\/\\/www.alxafrica.com permanent;" $config_path
sed -i "/server_name _;/a \ \n    error_page 404 \/404.html;\n    location = \/404.html {\n        internal;\n    }\n" $config_path

# Restart Nginx to apply the changes
service nginx restart
