#!/usr/bin/env bash
#configure your Nginx server so that
#/redirect_me is redirecting to another page.

apt-get -y update
apt-get -y install nginx

#Nginx should be listening on port 80
sudo ufw allow 'HTTP' 

#HTML page
echo "Hello World!" > /var/www/html/index.html
echo "<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>Ceci n'est pas une page</h1>
</body>
</html>" > /var/www/html/404.html

#redirection confg
confg_path=/etc/nginx/sites-available/default
sed -i "/server_name _;/a \\\trewrite ^\\/redirect_me https:\\/\\/www.alxafrica.com permanent;" $confg_path

#Configure your Nginx server to have a custom 404 page 
ed -i '/server_name _;/a \ \n    error_page 404 \/404.html;\n    location = \/404.html {\n        internal;\n    }\n' /etc/nginx/sites-available/default

#restart nginx
service nginx restart
