#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header


custom_header='add_header X-Served-By $hostname;'
nginx_config='/etc/nginx/sites-available/default'

sudo sed -i "/server_name _;/a \\\t$HEADER_CONFIG" nginx_config
