#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header

# shellcheck disable=SC2154

sudo apt-get update
sudo apt-get install -y nginx

#configue listening on port 80
ufw allow 'HTTP'

echo "Hello World!" > /var/www/html/index.html

custom_header='add_header X-Served-By $hostname;'
nginx_config='/etc/nginx/sites-available/default'

sudo sed -i "/server_name _;/a \\\t$custom_header" $nginx_config

service nginx restart
