#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Get the hostname
HOSTNAME=$(hostname)

# Add custom header
sudo sed -i "/http {/a \ \ \ \ add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

# Restart Nginx to apply the changes
sudo service nginx restart
