#!/usr/bin/env bash
# This script installs and configures HAProxy to distribute traffic between web-01 and web-02 using the roundrobin algorithm.

sudo apt-get update
sudo apt-get install -y haproxy

# Backup 
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Configure HAProxy
sudo bash -c 'cat <<EOT >> /etc/haproxy/haproxy.cfg

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 492381-web-01 52.3.249.236:80 check
    server 492381-web-02 100.25.20.88:80 check
EOT'

# Enable and start HAProxy 
sudo systemctl enable haproxy
sudo systemctl start haproxy