#!/usr/bin/env bash
# This script installs and configures HAProxy to distribute traffic between web-01 and web-02 using the roundrobin algorithm.

# Update and install necessary packages
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy



# Enable HAProxy service
sudo update-rc.d haproxy defaults

# Start HAProxy service
sudo service haproxy start
