#!/usr/bin/env bash
#Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs

#update and install nginx if not installed
apt-get update && apt-get install -y nginx

#enable traffic ib port 80

sudo ufw allow 'HTTP'

#set nginx to listen on all  IPv4 IPs on port 80
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sed -i '/listen \[::\]:80 default_server;/a \    listen 80;' /etc/nginx/sites-available/default
#restart nginx
service nginx restart
