#!/usr/bin/env bash
#Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
# a Bash script that configures a server to the above requirements

#update and install nginx if not installed
apt-get update && apt-get install -y nginx

#enable traffic ib port 80

ufw allow'HTTP'

#restart nginx
service nginx restart
