#!/usr/bin/env bash
# Bash script that configures an Ubuntu server

#backup the original host file
cp /etc/hosts /etc/hosts.backup
#editing /etc/hosts
sed -i '/localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
