#!/usr/bin/env bash
# Bash script that configures an Ubuntu server

#backup the original host file
cp /etc/hosts /etc/hosts.backup
#editing /etc/hosts
sed -i 's/localhost/127.0.0.2 localhost' /etc/hosts
sed -i 's/facebook.com/8.8.8.8 facebook.com' /etc/hosts
